# Generated by Django 5.1.2 on 2024-10-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_stock_stockproduct_delete_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockproduct',
            name='quantity',
        ),
    ]
